name: Test


on:
  push:
    branches:
      - main


jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        
      - name: Set dns for Mongo URI lookup resolution
        run: |
          sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
        
      - name: Create Zipped MongoDump
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: mongodump --uri $MONGODB_URI --archive=my_db_name_08_12_2020.zip

      - name: Check
        run: ls -lah
