name: Test


on:
  push:
    branches:
      - main


jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        
      - name: Set dns for Mongo URI lookup resolution
        run: |
          sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
        
      - name: Create MongoDump
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: mongodump --uri $MONGODB_URI
      
      - name: Check
        run: cd dump/experience && ls -la
